name: Flutter Web GitHub Pages Deploy

on:
  push:
    branches:
      - main
      - master
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false # Ensure gitmodules failure is ignored

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href /mahjong-score/

      - name: Sync build to docs and commit
        run: |
          rm -rf docs/*
          cp -r build/web/* docs/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          if git diff --staged --quiet; then
            echo "No changes in docs to commit"
          else
            git commit -m "chore: [CI] Auto-deploy build to docs folder"
            git push origin ${{ github.ref_name }}
          fi
